version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontEnd/workout-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontEnd/workout-app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
